lab1
iMaanick/Operating-Systems-labs-2023 pull request #1
Opened 2023-10-22 07:52 UTC by iMaanick

2023-10-23 16:45 UTC, DariaWelt requested changes
Нужно сделать класс демона синглтоном

2023-10-23 16:45 UTC, DariaWelt commented on lab1/lab1.cpp
> +std::string config_path;
Лучше убрать глобальные переменные и pid_file_path явно константа времени компиляции.

2023-10-23 16:45 UTC, DariaWelt commented on lab1/lab1.cpp
> +    if (name.length() != 0 && stat(name.c_str(), &buffer) == 0)
можно просто return без if

2023-10-28 12:37 UTC, DariaWelt requested changes
Есть ли у Вас аргументы, что работа не списана [отсюда](https://github.com/Hembos/Operating-Systems-labs/tree/56fbf81cba92e2e60fddafb5e275e117545d0f53/Popov.Ivan/lab1)?

2023-10-28 13:04 UTC, iMaanick commented
> Есть ли у Вас аргументы, что работа не списана [отсюда](https://github.com/Hembos/Operating-Systems-labs/tree/56fbf81cba92e2e60fddafb5e275e117545d0f53/Popov.Ivan/lab1)?

Посмотрев ссылки, которые были оставлены по синглтону, я не до конца понял как его нужно реализовать и изучил, как это было сделано в прошлом году. Ключевые функции, непосредственно выполняющее функционал лабы были написаны мной и это можно отследить по истории коммитов.

2023-10-28 15:03 UTC, DariaWelt approved these changes
Так получается, что основной функционал лабы это как раз демонизация. Работа принимается, замечаний по текущей реализации нет. За списывание вычитаю 2 балла, работы практически идентичны

В следующий раз рекомендую изменить код при заимствовании

2023-10-28 15:04 UTC, merged